name: Build GDExtension

on:
  workflow_dispatch:
    inputs:
      godotsteam_version:
        description: 'Steam Multiplayer Peer Tag'
        required: true
        type: string
        default: '0.0.1'

  pull_request:
  push:
    branches:
      - main

env:
  LIBNAME: steam-multiplayer-peer

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - platform: linux
            arch: x86_64
            os: ubuntu-24.04

          - platform: linux
            arch: arm64
            os: ubuntu-24.04-arm

          - platform: windows
            arch: x86_64
            os: windows-latest

          - platform: macos
            arch: x86_64
            os: macos-15-intel

          - platform: macos
            arch: arm64
            os: macos-15

        target-type:
          - template_debug
          - template_release

        float-precision:
          - single
          - double

    runs-on: ${{ matrix.target.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Checkout Steamworks SDK
        uses: actions/checkout@v7
        with:
          repository: EamonnER/steamworks-sdk
          token: ${{ secrets.STEAMWORKS_SDK_TOKEN }}
          path: steamworks

      - name: Copy Steamworks SDK
        shell: bash
        run: |
          cp -r steamworks/steamworks_sdk_165/sdk/public steam-multiplayer-peer/sdk/
          cp -r steamworks/steamworks_sdk_165/sdk/redistributable_bin steam-multiplayer-peer/sdk/

      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          em-version: 3.1.62

      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      - name: Build GDExtension
        shell: bash
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons \
            target=${{ matrix.target-type }} \
            platform=${{ matrix.target.platform }} \
            arch=${{ matrix.target.arch }} \
            precision=${{ matrix.float-precision }}

      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      - name: Windows - Delete compilation files
        if: ${{ matrix.target.platform == 'windows' }}
        shell: pwsh
        run: |
          Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force -ErrorAction SilentlyContinue

      - name: Package Steam API runtime
        shell: bash
        run: |
          mkdir -p bin/runtime

          if [ "${{ matrix.target.platform }}" = "windows" ]; then
            cp steamworks/steamworks_sdk_165/sdk/redistributable_bin/win64/steam_api64.dll \
              bin/runtime/
          elif [ "${{ matrix.target.platform }}" = "linux" ]; then
            if [ "${{ matrix.target.arch }}" = "x86_64" ]; then
              cp steamworks/steamworks_sdk_165/sdk/redistributable_bin/linux64/libsteam_api.so \
                bin/runtime/
            else
              cp steamworks/steamworks_sdk_165/sdk/redistributable_bin/linuxarm64/libsteam_api.so \
                bin/runtime/
            fi
          elif [ "${{ matrix.target.platform }}" = "macos" ]; then
            cp steamworks/steamworks_sdk_165/sdk/redistributable_bin/osx/libsteam_api.dylib \
              bin/runtime/
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: steam-multiplayer-peer-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.float-precision }}-${{ matrix.target-type }}
          path: |
            ${{ github.workspace }}/bin/**

  merge:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v7
        with:
          name: steam-multiplayer-peer
          pattern: steam-multiplayer-peer-*
          delete-merged: true
